package com.procsin.DB.Entity.Pack.Return;

public enum ReturnedOrderStatus {
    MUSTERI_HIZMETLERI_BEKLENIYOR,
    YENIDEN_CIKIS_BEKLENIYOR,
    YENIDEN_CIKIS_SAGLANDI,
    KISMI_GONDERIM_BEKLENIYOR,
    KISMI_GONDERIM_SAGLANDI,
    TESLIM_ALINMAYAN_SIPARIS,
    GIDER_PUSULASI_KESILDI,
    MANUEL_OLUSTURULDU
}
